version: '3'
services:
  app:
    container_name: uhuu
    build:
      context: ./
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET=GKDZlvIsWesjLiHANMTsVWFvc4IH4GULnqfrpV028mcMFF3xuNYq6zVlsbnfwVNd
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=uhuu
      - DB_USERNAME=root
      - DB_PASSWORD=123456
    networks:
      - laravel
    depends_on:
      - mysql
  mysql:
      container_name: mysql-uhuu
      image: 'mysql:8.0'
      environment:
        MYSQL_ROOT_PASSWORD: "123456"
        MYSQL_DATABASE: "uhuu"
      ports:
        - 3306:3306
      networks:
        - laravel
networks:
    laravel:
        driver: bridge
volumes:
    mysql8:
        driver: local
